# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@root"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@srv"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@cache"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/var/lib/machines" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@machines"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/var/lib/portables" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@portables"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/disk/by-uuid/84a6325c-7323-422f-856c-bb74f670e9a7";
    fsType = "btrfs";
    options = [
      "subvol=@tmp"
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3d461431-b3d2-40ed-bd12-248afbc16593";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/media/extra" = {
    device = "/dev/disk/by-uuid/ae4ce961-59c0-4e37-a453-04ba8df975fc";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BBD8-9E68";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      options = [ "discard=async" ];
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
